version: '3.8'

services:
  backend:
    build:
      context: ../../
      dockerfile: ./infra/docker/Dockerfile
    command: yarn start
    ports:
      - '8000:8000'
      - '9229:9229'
    env_file: ['../../configs/docker.env']
    # depends_on: ['db', 'mailhog']
    depends_on: ['db']
    volumes: ['../../:/appPlugin']
    # environment:
    #     MODE: application
    #     PORT: 8000
    #     DB_HOST: db
    #     MAIL_HOST: mailhog
